### ISSUE TITLE
Problems with the hijack file

### ISSUE THREAD

**Issue by DynamicBit** [crmulliner/adbi#10]
Hello,
Iam following the manual to test the adbi toolkit. But every time, at the point with the hijack file "./hijack -d -p PID -l /data/local/tmp/libexample.so" Iam getting theses error message "error usage: ./hijack -p PID -l LIBNAME [-d (debug on)] [-z (zygote)] [-m (no mprotect)] [-s (appname)] [-Z (trace count)] [-D (debug level)]". Iam having no idea whats the problem, please can someone help me.

**Comment by leepood** [comment]
@DynamicBit  `-p PID` means the process id of your target ,not the symbol "PID" you can find the pid by `ps `
